language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update php-coveralls/php-coveralls:"^1.1 || ^2.0"
  - travis_retry composer install --no-interaction --prefer-dist --no-progress --no-suggest

before_script:
  - mkdir -p build/logs

script:
  - composer run test-ci

after_success:
  - [ -f vendor/bin/php-coveralls ] && travis_retry php vendor/bin/php-coveralls -v || travis_retry php vendor/bin/coveralls -v
